"""empty message

Revision ID: 20e888c3de75
Revises: 4f2508f18838
Create Date: 2020-03-31 10:59:58.320463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e888c3de75'
down_revision = '4f2508f18838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifies')
    # ### end Alembic commands ###
