"""empty message

Revision ID: ceac0c740a1a
Revises: 20e888c3de75
Create Date: 2020-04-12 02:21:47.422407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac0c740a1a'
down_revision = '20e888c3de75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'status')
    # ### end Alembic commands ###
